"""
Django settings for BackendProject project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

try:
 #  SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
    SECRET_KEY = os.environ["SECRET_KEY"]
except KeyError as e:
    raise RuntimeError("Could not find a SECRET_KEY in environment") from e


# SECRET_KEY = 'django-insecure-)%xomtp^+6!yk-keu4fuz27!0c8k@#3l*)g26ymghu+37l4j7u'

# try:
#     SECRET_KEY = os.environ["SECRET_KEY"]
# except KeyError as e: 
#     raise RuntimeError("Could not find a SECRET_KEY in environment") from e
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# IP DE AWS SGV-WMS-BACKEND
ALLOWED_HOSTS = ["backweb.copernicowms.com", "127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'BackendApp',
    'BackendGuias',
    'wmsAdapter',
    'siesa'
]

CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'BackendApp.middleware.MiddlewarePerzonalizado',
    'BackendProject.middleware.MiddlewarePerzonalizado',
]

ROOT_URLCONF = 'BackendProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BackendProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'SANDBOX_BASE',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'azk': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_AZK_BASE',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'ecdrp_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'EC_DRP_ADAPTER',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'ecdrp': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'EC_DRP_BASE',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'azk_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_AZK_ADAPTER',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'rpz': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_RPZ_WMS_BASE',
        'USER': 'sa',
        'PASSWORD': 'Soporte2012',
        'HOST': '190.144.126.58',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'rpz_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_RPZ_ADAPTER',
        'USER': 'sa',
        'PASSWORD': 'Soporte2012',
        'HOST': '190.144.126.58',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
	'idc': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_IDC_WMS_BASE',
        'USER': 'SGV',
        'PASSWORD': 'WMS2019+',
        'HOST': '40.75.66.66',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'idc_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_IDC_ADAPTER',
        'USER': 'SGV',
        'PASSWORD': 'WMS2019+',
        'HOST': '40.75.66.66',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'aqu': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_AQU_BASE',
        'USER': 'AquaSQL',
        'PASSWORD': 'Sa123456',
        'HOST': 'iaaslabaqua.siesacloud.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'aqu_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_AQU_ADAPTER',
        'USER': 'AquaSQL',
        'PASSWORD': 'Sa123456',
        'HOST': 'iaaslabaqua.siesacloud.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
	'mtl': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_MTL_BASE',
        'USER': 'MontolivoDB',
        'PASSWORD': 'Sa123456',
        'HOST': '52.3.216.105',
        'PORT': '20446',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'mtl_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_MTL_ADAPTER',
        'USER': 'MontolivoDB',
        'PASSWORD': 'Sa123456',
        'HOST': '52.3.216.105',
        'PORT': '20446',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'mdc' : {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_MDC_WMS_BASE',
        'USER': 'wmsadmin',
        'PASSWORD': 'Q4ndKU38#Ij5rmR$x2',
        'HOST': '52.20.208.212', #apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com
        # 'HOST' : 'apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'mdc_adapter' : {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_MDC_DATA_ADAPTER',
        'USER': 'wmsadmin',
        'PASSWORD': 'Q4ndKU38#Ij5rmR$x2',
        'HOST': '52.20.208.212', #apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com
        #'HOST' : 'apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'mdcp' : {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_MDC_PWMS_BASE',
        'USER': 'wmsadmin',
        'PASSWORD': 'Q4ndKU38#Ij5rmR$x2',
        'HOST': '52.20.208.212', #apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com
        # 'HOST' : 'apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'mdcp_adapter' : {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_MDC_PDATA_ADAPTER',
        'USER': 'wmsadmin',
        'PASSWORD': 'Q4ndKU38#Ij5rmR$x2',
        'HOST': '52.20.208.212', #apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com
        #'HOST' : 'apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'mdcg' : {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_MDC_GWMS_BASE',
        'USER': 'wmsadmin',
        'PASSWORD': 'Q4ndKU38#Ij5rmR$x2',
        'HOST': '52.20.208.212', #apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com
        # 'HOST' : 'apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'mdcg_adapter' : {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_MDC_GDATA_ADAPTER',
        'USER': 'wmsadmin',
        'PASSWORD': 'Q4ndKU38#Ij5rmR$x2',
        'HOST': '52.20.208.212', #apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com
        #'HOST' : 'apolo2.cdsg9ojk5pmy.us-east-1.rds.amazonaws.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'usp' : {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_USP_BASE',
        'USER': 'sa',
        'PASSWORD': 's0p0rte@2022!',
        'HOST': '20.65.67.220',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'usp_adapter' : {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_USP_ADAPTER',
        'USER': 'sa',
        'PASSWORD': 's0p0rte@2022!',
        'HOST': '20.65.67.220', 
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    # 'mdc2': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_MDC_GWMS_BASE',
    #     'USER': 'sgv.aws.test',
    #     'PASSWORD': 's.Fg34GvHT.a4.GwXK*s.3tt41',
    #     'HOST': '200.122.197.82,1433',
    #     'PORT': '',
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    # 'mdc': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_MDC_WMS_BASE',
    #     'USER': 'sgvsoftware',
    #     'PASSWORD': 'S*GVS0ftw4re*',
    #     'HOST': '200.122.197.82,1433',
    #     'PORT': '',
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    # 'mtl': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_MTL_WMS_BASE',
    #     'USER': 'sgvsoftware',
    #     'PASSWORD': 'Sgv2019.',
    #     'HOST': '67.227.194.244',
    #     'PORT': '',
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    # 'mtl_adapter': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_MTL_WMS_ADAPTER',
    #     'USER': 'sgvsoftware',
    #     'PASSWORD': 'Sgv2019.',
    #     'HOST': '67.227.194.244',
    #     'PORT': '',
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    'bon': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_BON_BASE',
        'USER': 'sgv',
        'PASSWORD': 'Svg2020*%',
        'HOST': 'IaasInversisa.siesacloudservices.com,20446',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'bon_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_BON_ADAPTER',
        'USER': 'sgv',
        'PASSWORD': 'Svg2020*%',
        'HOST': 'IaasInversisa.siesacloudservices.com,20446',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    # 'mtl': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_MTL_BASE',
    #     'USER': 'sa',
    #     'PASSWORD': 'Sa123456',
    #     'HOST': 'server.restaurantemontolivo.com',
    #     'PORT': '',
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    # 'mtl_adapter': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_MTL_ADAPTER',
    #     'USER': 'sa',
    #     'PASSWORD': 'Sa123456',
    #     'HOST': 'server.restaurantemontolivo.com',
    #     'PORT': '',
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    'dll': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DLL_BASE',
        'USER': 'sgvsoftware',
        'PASSWORD': 'Sgv2019.',
        'HOST': '67.227.194.244',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'dll_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DLL_ADAPTER',
        'USER': 'sgvsoftware',
        'PASSWORD': 'Sgv2019.',
        'HOST': '67.227.194.244',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'dll6': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DLL_DACPAC_BASE_6',
        'USER': 'sgvsoftware',
        'PASSWORD': 'Sgv2019.',
        'HOST': '67.227.194.244',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'dll6_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DLL_DACPAC_ADAPTER_6',
        'USER': 'sgvsoftware',
        'PASSWORD': 'Sgv2019.',
        'HOST': '67.227.194.244',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'cra': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_CRA_BASE',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'cra_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_CRA_ADAPTER',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'jrp': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_JRP_BASE',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'jrp_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_JRP_ADAPTER',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'jrp_prb': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_JRP_BASE_prueba',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'jrp_prb_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_JRP_ADAPTER_prueba',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'sml': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_SML_WMS_BASE',
        'USER': 'sgvsoftware',
        'PASSWORD': 'Sgv2019.',
        'HOST': '67.227.194.244',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'sml_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_SML_WMS_ADAPTER',
        'USER': 'sgvsoftware',
        'PASSWORD': 'Sgv2019.',
        'HOST': '67.227.194.244',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    # 'pqd': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_PQD_BASE',
    #     'USER': 'sa',
    #     'PASSWORD': 'Sa123456',
    #     'HOST': 'iaasproquident.siesacloud.com',
    #     'PORT': '20446',
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 17 for SQL Server',
    #     }
    # },
    'pqd': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_PQD_BASE',
        'USER': 'sa',
        'PASSWORD': 'Sa123456',
        'HOST': '3.213.230.165',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        }
    },
    'pqd_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_PQD_WMS_ADAPTER',
        'USER': 'sa',
        'PASSWORD': 'Sa123456',
        'HOST': '3.213.230.165',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        }
    },
    'bbl': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'US_BBL_BASE',
        'USER': 'sgvsoftware',
        'PASSWORD': 'Sgv2019.',
        'HOST': '67.227.194.244',
        'PORT': '',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'bbl_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'US_BBL_ADAPTER',
        'USER': 'sgvsoftware',
        'PASSWORD': 'Sgv2019.',
        'HOST': '67.227.194.244',
        'PORT': '',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'pth': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_PTH_BASE',
        'USER': 'sgvsoftware',
        'PASSWORD': '56z1Cpqd1QdmiAGn',
        'HOST': '190.109.22.18',
        'PORT': '11443',
        # 'HOST': '192.168.20.233',
        # 'PORT': '1433',

        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'pth_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_PTH_ADAPTER',
        'USER': 'sgvsoftware',
        'PASSWORD': '56z1Cpqd1QdmiAGn',
        'HOST': '190.109.22.18',
        'PORT': '11443',
        # 'HOST': '192.168.20.233',
        # 'PORT': '1433',

        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'pth_siesa': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'UnoEE',
        'USER': 'sgvsoftware',
        'PASSWORD': '56z1Cpqd1QdmiAGn',
        # 'HOST': '190.109.22.18',
        # 'PORT': '11443',
        'HOST': '192.168.20.233',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'dvd': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DVD_BASE',
        'USER': 'DvidaWMS',
        'PASSWORD': 'ExMCX6ht3WmaQmUixSKg',
        'HOST': '186.147.143.184',
        'PORT': '8000',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'dvd_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DVD_ADAPTER',
        'USER': 'DvidaWMS',
        'PASSWORD': 'ExMCX6ht3WmaQmUixSKg',
        'HOST': '186.147.143.184',
        'PORT': '8000',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'dth': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DTH_BASE',
        'USER': 'copernico',
        'PASSWORD': '3zgV4Zot3yUoQFnC97Je',
        'HOST': '52.6.130.130',
        'PORT': '11433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'dth_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DTH_ADAPTER',
        'USER': 'copernico',
        'PASSWORD': '3zgV4Zot3yUoQFnC97Je',
        'HOST': '52.6.130.130',
        'PORT': '11433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },

    'ppn': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'US_PPN_BASE',
        'USER': 'USPPN',
        'PASSWORD': 'T6LkcnLnqjb5uMzMCCmj',
        'HOST': '3.237.94.74',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'ppn_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'US_PPN_ADAPTER',
        'USER': 'USPPN',
        'PASSWORD': 'T6LkcnLnqjb5uMzMCCmj',
        'HOST': '3.237.94.74',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'ymh_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_YMH_ADAPTER',
        'USER': 'sgvsoftware',
        'PASSWORD': 'hRCVCpb8h3F4Hq6F3Pdi',
        'HOST': '3.237.94.74',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'ymh': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_YMH_BASE',
        'USER': 'sgvsoftware',
        'PASSWORD': 'hRCVCpb8h3F4Hq6F3Pdi',
        'HOST': '3.237.94.74',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'pmc_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_PMC_ADAPTER',
        'USER': 'copernicoPMC',
        'PASSWORD': 'orBPCLdMXqK92wUAHwFb',
        'HOST': '67.225.136.55',
        'PORT': '1962',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'pmc': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_PMC_BASE',
        'USER': 'copernicoPMC',
        'PASSWORD': 'orBPCLdMXqK92wUAHwFb',
        'HOST': '67.225.136.55',
        'PORT': '1962',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'cmk_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_CMK_ADAPTER',
        'USER': 'copernicoPMC',
        'PASSWORD': 'orBPCLdMXqK92wUAHwFb',
        'HOST': '67.225.136.55',
        'PORT': '1962',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'cmk': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_CMK_WMS_BASE',
        'USER': 'copernicoPMC',
        'PASSWORD': 'orBPCLdMXqK92wUAHwFb',
        'HOST': '67.225.136.55',
        'PORT': '1962',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'clb_600_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_CLB_0600_ADAPTER',
        'USER': 'copernicoCLB0600',
        'PASSWORD': 'dKtR9hgQgz6bWaRduSdV',
        'HOST': '67.225.136.55',
        'PORT': '1962',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'clb_600': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_CLB_0600_BASE',
        'USER': 'copernicoCLB0600',
        'PASSWORD': 'dKtR9hgQgz6bWaRduSdV',
        'HOST': '67.225.136.55',
        'PORT': '1962',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'ist': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_IST_BASE',
        'USER': 'COIST',
        'PASSWORD': 'AuM84yNavBPXSX8TKcAg',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'ist_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_IST_ADAPTER',
        'USER': 'COIST',
        'PASSWORD': 'AuM84yNavBPXSX8TKcAg',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'drp': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'MX_DRP_BASE',
        'USER': 'MXDRP',
        'PASSWORD': 'P5q6qYGdyvpqYPFvtEbE',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'drp_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'MX_DRP_ADAPTER',
        'USER': 'MXDRP',
        'PASSWORD': 'P5q6qYGdyvpqYPFvtEbE',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'sandbox': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'SANDBOX_BASE',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },

    'sandbox_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'SANDBOX_ADAPTER',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'sandboxbbl': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'US_BBL_BASE',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },

    'sandboxbbl_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'US_BBL_ADAPTER',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'btp_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'US_BTP_ADAPTER',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'btp': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'US_BTP_BASE',
        'USER': 'SANDBOX',
        'PASSWORD': 'EqEMCuBxaFwxxFVhk4Fj',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'rymelMP': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_RYMELMP_BASE',
        'USER': 'usrSVG',
        'PASSWORD': '3fA4fvkvlBgWCPc1AM2h',
        'HOST': 'bdrymel.eastus.cloudapp.azure.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'rymelMP_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_RYMEL_ADAPTER',
        'USER': 'usrSVG',
        'PASSWORD': '3fA4fvkvlBgWCPc1AM2h',
        'HOST': 'bdrymel.eastus.cloudapp.azure.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },

    # 'rymelPT_adapter': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_RYMEL_APS_ADAPTER',
    #     'USER': 'usrSVG',
    #     'PASSWORD': '3fA4fvkvlBgWCPc1AM2h',
    #     'HOST': 'bdrymel.eastus.cloudapp.azure.com',
    #     'PORT': '1433',
    #     'OPTIONS': {
    #             'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    # 'rymelPT_adapter': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_RYMEL_ADAPTER',
    #     'USER': 'usrSVG',
    #     'PASSWORD': '3fA4fvkvlBgWCPc1AM2h',
    #     'HOST': 'bdrymel.eastus.cloudapp.azure.com',
    #     'PORT': '1433',
    #     'OPTIONS': {
    #             'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    #     'rymelPT': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_RYMEL_APS_BASE',
    #     'USER': 'usrSVG',
    #     'PASSWORD': '3fA4fvkvlBgWCPc1AM2h',
    #     'HOST': 'bdrymel.eastus.cloudapp.azure.com',
    #     'PORT': '1433',
    #     'OPTIONS': {
    #             'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },

    # 'rymelPT_local_adapter': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_RYMEL_ADAPTER',
    #     'USER': 'usrSVG',
    #     'PASSWORD': '3fA4fvkvlBgWCPc1AM2h',
    #     'HOST': 'bdrymel.eastus.cloudapp.azure.com',
    #     'PORT': '1433',
    #     'OPTIONS': {
    #             'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    #     'rymelPT_local': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': 'CO_RYMEL_APS_BASE',
    #     'USER': 'usrSVG',
    #     'PASSWORD': '3fA4fvkvlBgWCPc1AM2h',
    #     'HOST': 'bdrymel.eastus.cloudapp.azure.com',
    #     'PORT': '1433',
    #     'OPTIONS': {
    #             'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # },
    'codrp': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DRP_BASE',
        'USER': 'CODRP',
        'PASSWORD': 'QPHroJaGvSAJpaRQyq2x',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'codrp_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_DRP_ADAPTER',
        'USER': 'CODRP',
        'PASSWORD': 'QPHroJaGvSAJpaRQyq2x',
        'HOST': 'host.copernicowms.com',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'osk': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_OSK_BASE',
        'USER': 'copernicowms',
        'PASSWORD': 'o5Ff6AEn8nVVBefgQ2kv',
        'HOST': '201.184.246.18',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'osk_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_OSK_ADAPTER',
        'USER': 'copernicowms',
        'PASSWORD': 'o5Ff6AEn8nVVBefgQ2kv',
        'HOST': '201.184.246.18',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'osk_local': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_OSK_BASE',
        'USER': 'copernicowms',
        'PASSWORD': 'o5Ff6AEn8nVVBefgQ2kv',
        'HOST': '201.184.246.18',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'osk_local_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_OSK_ADAPTER',
        'USER': 'copernicowms',
        'PASSWORD': 'o5Ff6AEn8nVVBefgQ2kv',
        'HOST': '201.184.246.18',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'byn': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_BYN_BASE',
        'USER': 'lsadmin',
        'PASSWORD': 'Lsadmin2022**.',
        'HOST': '104.215.88.189',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'byn_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_BYN_ADAPTER',
        'USER': 'lsadmin',
        'PASSWORD': 'Lsadmin2022**.',
        'HOST': '104.215.88.189',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },  
    'qp': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_QP_WMS_BASE',
        'USER': 'sa',
        'PASSWORD': 'sa2012',
        'HOST': '181.205.242.197',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'qp_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_QP_ADAPTER',
        'USER': 'sa',
        'PASSWORD': 'sa2012',
        'HOST': '181.205.242.197',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'smt': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_SMT_WMS_BASE',
        'USER': 'sa',
        'PASSWORD': 'Drainage*2Sycamore*2Landfill*2Retorted*2Saddlebag*2Speed',
        'HOST': '54.166.21.22',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'smt_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_SMT_DATA_ADAPTER',
        'USER': 'sa',
        'PASSWORD': 'Drainage*2Sycamore*2Landfill*2Retorted*2Saddlebag*2Speed',
        'HOST': '54.166.21.22',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'pasmt': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'PA_SMT_BASE',
        'USER': 'sa',
        'PASSWORD': 'Drainage*2Sycamore*2Landfill*2Retorted*2Saddlebag*2Speed',
        'HOST': '54.147.171.135',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'pasmt_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'PA_SMT_ADAPTER',
        'USER': 'sa',
        'PASSWORD': 'Drainage*2Sycamore*2Landfill*2Retorted*2Saddlebag*2Speed',
        'HOST': '54.147.171.135',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    
        'usp': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_USP_BASE',
        'USER': 'sa',
        'PASSWORD': 's0p0rte@2022!',
        'HOST': '20.65.67.220',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
        'usp_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_USP_ADAPTER',
        'USER': 'sa',
        'PASSWORD': 's0p0rte@2022!',
        'HOST': '20.65.67.220',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
           'usp_local': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_USP_BASE',
        'USER': 'sa',
        'PASSWORD': 's0p0rte@2022!',
        'HOST': '20.65.67.220',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
        'usp_adapter_local': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_USP_ADAPTER',
        'USER': 'sa',
        'PASSWORD': 's0p0rte@2022!',
        'HOST': '20.65.67.220',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'usp_sandbox_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_USP_SANDBOX_ADAPTER',
        'USER': 'sa',
        'PASSWORD': 's0p0rte@2022!',
        'HOST': '20.65.67.220',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'usp_sandbox': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_USP_SANDBOX_BASE',
        'USER': 'sa',
        'PASSWORD': 's0p0rte@2022!',
        'HOST': '20.65.67.220',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'crj_prueba': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_CRA_BASE',
        'USER': 'sa',
        'PASSWORD': 'CRSant..',
        'HOST': '190.0.13.190\copernico',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                # "extra_params": 'Encrypt=no;TrustServerCertificate=yes;Connection Timeout=30'
        },
    },
        'crj_prueba_adapter': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'CO_CRA_BASE',
        'USER': 'sa',
        'PASSWORD': 'CRSant..',
        'HOST': '190.0.13.190\copernico',
        'PORT': '1433',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Bogota'

USE_I18N = True


USE_L10N = True


USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
