# from django.db import models
# from siesa.models import T200MmTerceros

# class T202MmProveedores(models.Model):
#     f202_id_cia = models.ForeignKey('T277CoTipoProv', models.DO_NOTHING, db_column='f202_id_cia')
#     f202_rowid_tercero = models.OneToOneField(T200MmTerceros, models.DO_NOTHING, db_column='f202_rowid_tercero', primary_key=True)
#     f202_id_sucursal = models.CharField(max_length=3)
#     f202_descripcion_sucursal = models.CharField(max_length=40)
#     f202_ind_estado = models.SmallIntegerField()
#     f202_id_moneda = models.ForeignKey(T017MmMonedas, models.DO_NOTHING, db_column='f202_id_moneda')
#     f202_id_clase_proveedor = models.CharField(max_length=4, blank=True, null=True)
#     f202_rowid_contacto = models.ForeignKey(T015MmContactos, models.DO_NOTHING, db_column='f202_rowid_contacto', blank=True, null=True)
#     f202_id_cond_pago = models.CharField(max_length=3, blank=True, null=True)
#     f202_dias_gracia = models.SmallIntegerField()
#     f202_cupo_credito = models.DecimalField(max_digits=19, decimal_places=4)
#     f202_id_tipo_prov = models.ForeignKey('T277CoTipoProv', models.DO_NOTHING, db_column='f202_id_tipo_prov')
#     f202_ind_forma_pago = models.SmallIntegerField()
#     f202_rowid_pe_default = models.ForeignKey('T633PeProvCuenta', models.DO_NOTHING, db_column='f202_rowid_pe_default', blank=True, null=True)
#     f202_ind_consignacion = models.SmallIntegerField()
#     f202_id_banco = models.ForeignKey(T016MmBancos, models.DO_NOTHING, db_column='f202_id_banco', blank=True, null=True)
#     f202_cuenta = models.CharField(max_length=25, blank=True, null=True)
#     f202_nombre_cuenta = models.CharField(max_length=50, blank=True, null=True)
#     f202_id_cpto_imp_iva = models.SmallIntegerField(blank=True, null=True)
#     f202_id_cpto_imp_rf = models.SmallIntegerField(blank=True, null=True)
#     f202_id_cpto_imp_ica = models.SmallIntegerField(blank=True, null=True)
#     f202_notas = models.CharField(max_length=255, blank=True, null=True)
#     f202_fecha_ingreso = models.DateTimeField()
#     f202_porcentaje_exceso_compra = models.DecimalField(max_digits=5, decimal_places=2)
#     f202_rowid_movto_entidad = models.IntegerField(blank=True, null=True)
#     f202_monto_anual_compra = models.DecimalField(max_digits=19, decimal_places=4)
#     f202_ind_monto_anual_compra = models.SmallIntegerField()
#     f202_ts = models.DateTimeField()
#     f202_ind_exige_cotiz_en_oc = models.SmallIntegerField()
#     f202_ind_exige_oc_en_ea = models.SmallIntegerField()
#     f202_ind_cat_tributaria = models.SmallIntegerField()
#     f202_ind_declarante = models.SmallIntegerField()
#     f202_porcentaje_fijo_rete = models.DecimalField(max_digits=6, decimal_places=2)
#     f202_vlr_prom_salud_ant_ano = models.DecimalField(max_digits=19, decimal_places=4)
#     f202_vlr_salud_prepagada = models.DecimalField(max_digits=19, decimal_places=4)
#     f202_vlr_int_vivienda = models.DecimalField(max_digits=19, decimal_places=4)
#     f202_vlr_dependientes = models.DecimalField(max_digits=19, decimal_places=4)
#     f202_id_llave_ret_indep = models.ForeignKey(T040MmLlavesRetencion, models.DO_NOTHING, db_column='f202_id_llave_ret_indep', blank=True, null=True)
#     f202_ind_bloqueo_pago = models.SmallIntegerField()
#     f202_ind_oc_exige_edi = models.SmallIntegerField()
#     f202_id_grupo_co_cm = models.ForeignKey('T222GrupoEntidad', models.DO_NOTHING, db_column='f202_id_grupo_co_cm', blank=True, null=True)
#     f202_ind_tipo_grupo_co_cm = models.ForeignKey('T222GrupoEntidad', models.DO_NOTHING, db_column='f202_ind_tipo_grupo_co_cm')
#     f202_ind_defecto_pe_trco = models.SmallIntegerField()
#     f202_ind_exige_consig = models.SmallIntegerField()
#     f202_ind_aviso_despacho = models.SmallIntegerField()
#     f202_ind_pago_efe_anual = models.SmallIntegerField()
#     f202_ind_gum_unificado = models.SmallIntegerField()

#     class Meta:
#         managed = False
#         db_table = 't202_mm_proveedores'
#         unique_together = (('f202_rowid_tercero', 'f202_id_sucursal'),)

