from BackendApp.views.warehouses import *
from BackendApp.views.descriptions import *
from BackendApp.views.picking import *
from BackendApp.views.dynamics import *
from BackendApp.views.employee import *
from BackendApp.views.users import *
from BackendApp.views.logisticsvar import *
from BackendApp.views.articles import *
from BackendApp.views.listasvigenciadespacho import *
from BackendApp.views.tiposdecaja import *
from BackendApp.views.inventory import *
from BackendApp.views.dwh_picking import *
from BackendApp.views.descriptoreslogisticos import *
from BackendApp.views.registrosanitario import *
from BackendApp.views.layout import *
from BackendApp.views.kpi_recibo import *
from BackendApp.views.kpi_picking import *
from BackendApp.views.kpi_layout import *
from BackendApp.views.statuscalidad import *
from BackendApp.views.kpi_aduana import *
from BackendApp.views.kpi_general import *
from BackendApp.views.guiatte import *
from BackendApp.views.epk import *
from BackendApp.views.euk import *
from BackendApp.views.api import *
from BackendApp.views.zpl import *
from BackendApp.views.epn import *
from BackendApp.views.pruebas import *
from BackendApp.views.import_data import *
from BackendApp.views.tables_fields import *
# from BackendApp.views.databases_list import *
from BackendApp.views.mongo import *
from BackendApp.views.tipodocto import *
from BackendApp.views.Orders import * 
from BackendApp.views.Flash import *  
from BackendApp.views.Details import * 
from BackendApp.views.conteosinventario import *
from BackendApp.views.autoaduana import *
from BackendApp.views.stored_procedures import *
from BackendApp.views.mantenimiento import *
from BackendApp.views.resurtido import *
from BackendApp.views.inventario import *
from BackendApp.views.testing import *
from BackendApp.views.coordenadas import *